### ISSUE TITLE
Docs Demo Flow deployment failed 

### ISSUE THREAD

**Issue by songhn233** [jina-ai/jcloud#114]
related issue: https://github.com/jina-ai/jina-hubble-sdk/issues/146

## Flow deployment failed

```bash
Please report this session_id: [yellow bold]f9e1e2c0-8f84-11ed-9b1e-26690b3fb236[/] to
https://github.com/jina-ai/jina-hubble-sdk/issues
Traceback (most recent call last):
  File "python3.9/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
```

#### Flow yaml
```yaml
jtype: Flow
version: '1'
gateway:
  protocol: [grpc, http, websocket]
  port: [54321, 54322, 54323]
executors:
  - uses: executor1/config.yml
    name: toyExecutor
```

#### Flow ID / Request ID
```text
Flow ID: N/A
Request ID: N/A
```

#### `jina` version
```bash
jina -vf
- jina 3.13.2
- docarray 0.20.1
- jcloud 0.1.6
- jina-hubble-sdk 0.29.0
- jina-proto 0.1.13
- protobuf 4.21.12
- proto-backend python
- grpcio 1.47.2
- pyyaml 6.0
- python 3.9.1
- platform Darwin
- platform-release 22.2.0
- platform-version Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022;
- architecture arm64
- processor arm
- internal False
```

**Comment by npitsillos** [comment]
@songhn233 thanks for reporting this issue! Could I ask you to list the commands you executed to get this error?

**Comment by songhn233** [comment]
> @songhn233 thanks for reporting this issue! Could I ask you to list the commands you executed to get this error?

@npitsillos I just follow [Jina Doc](https://docs.jina.ai/get-started/create-app/#deploy-to-jcloud) steps, run

```
jina cloud deploy ./
```

for the same project

**Comment by npitsillos** [comment]
@songhn233 I see. This will be fixed in the next `jina` release.

**Comment by songhn233** [comment]
> @songhn233 I see. This will be fixed in the next `jina` release. What you can do to get a working example now is to change the `flow.yml` file by changing from
> 
> ```
> jtype: Flow
> gateway:
>   protocol: [grpc, http, websocket]
>   port: [12345, 12346, 12347]
> executors:
>   - uses: executor1/config.yml
>     name: toyExecutor
> ```
> 
> to
> 
> ```
> jtype: Flow
> with:
>   protocol: http
> executors:
>   - uses: executor1/config.yml
>     name: toyExecutor
> ```

I tried this but it still failed, same error.

**Comment by npitsillos** [comment]
@songhn233 I get a similar error when I am not logged in using `jc login`. However, this was resolved when I logged in. Could you carry out these commands and let me know what the outcome is?

```
jina new hello
# change the flow.yml as shown
jc login -> login to jcloud
jina cloud deploy ./path/to/flow/folder
```
This should submit your flow 
![image](https://user-images.githubusercontent.com/9141826/212923678-5da44fa0-db80-4699-945e-c11e297015f5.png)

And the flow should be serving
![image](https://user-images.githubusercontent.com/9141826/212923812-e07a45de-88c7-44a4-a89e-1f99b1b0a4da.png)

Let me know if the commands I listed here work.

**Comment by songhn233** [comment]
@npitsillos Hello, the output I get from command looks different from yours, like the environment variable check and login status, which I'm sure has been updated to the latest version

<img width="429" alt="image" src="https://user-images.githubusercontent.com/47357585/213767979-47b31606-0719-4e7a-9039-59881d09934d.png">

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/47357585/213768393-6fa91e0e-3b74-484a-b025-a51c5dd64c20.png">

**Comment by songhn233** [comment]
> Can you show the output of the following commands? I am not sure what could be causing this so let's try using `jcloud` first to make sure everything is fine on pushing executors to `hubble` and deploying a flow.
> 
> ```
> jc new helloworld
> jc deploy helloworld
> ```

`jc new helloworld`:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/47357585/214333757-c1897c8a-5572-4031-acf5-ddc635a51dcc.png">

`jc deploy helloworld`:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/47357585/214334346-c8dfa1e4-a448-4172-aa6d-fbf6721ea106.png">

**Comment by npitsillos** [comment]
This might be an issue with the internet connection. If you could show which line in `hubble_sdk` causes the error would help in identifying the issue.

**Comment by npitsillos** [comment]
I will close this issue as there was no further activity. Please feel free to reopen if still facing issues.
