### ISSUE TITLE
bug: survey not working

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jcloud#129]
This is what I get when I try to fill out the survey

![Image](https://user-images.githubusercontent.com/11627845/221696501-f8f847eb-5069-4b07-b594-eeba94fc37cc.png)

**Comment by florian-hoenicke** [comment]
you should also accept lower case y

**Comment by npitsillos** [comment]
See the below screenshot.

![image](https://user-images.githubusercontent.com/9141826/229743278-3ba7e682-9896-440f-b98b-0ade27f4f2ca.png)
