### ISSUE TITLE
show what methods are allowed on an illegal call

### ISSUE THREAD

**Issue by fogx** [jina-ai/jcloud#69]
**Is your feature request related to a problem? Please describe.**
When calling illegal requests like `/` on Jina cloud, the following error fires:
`{"detail":"Method Not Allowed"}`

**Describe the solution you'd like**
it would be a good idea to show what methods are allowed. I really got confused because I
thought it meant HTTP methods like POST/GET etc.

**Comment by deepankarm** [comment]
@fogx This is related to [jina-ai/jina](https://github.com/jina-ai/jina) & FastAPI in general, unrelated to JCloud.

**Comment by fogx** [comment]
@deepankarm thank you for the clarification!
