### ISSUE TITLE
Allow to deploy flow with development branch of jina to do manual testing

### ISSUE THREAD

**Issue by samsja** [jina-ai/jcloud#77]
Hey team.

Atm we can't set a github branch as a valide jina version for jcloud. 

I would like to be able to test a development branch on jcloud. Right now I can only precise a released (on pypi) version.

According the our slack discussion I believe that the `VERSION` validation should be slightly changed https://github.com/jina-ai/wolf/blob/8baa0badb743399646084efb37e4eb44ef3d5b00/wolf/commons/models/jcloud/__init__.py#L88-L98

and that the `pip install jina[standard]==VERSION` could be move in the case of a git version to something like this `pip install jina+git:GIT_URL`

**Comment by deepankarm** [comment]
Supported with Operator.
