### ISSUE TITLE
feat: let the user define a name for deployment

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jcloud#85]
It would be helpful to let us configure names for the deployments. That way we have an easier time distinguishing all different deployments.

When running jc list, I get the following list:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11627845/192994594-eac3b91d-48e5-4f80-b399-6ff36d322ca4.png">
One of the deployments is for one of our customers, another one is an example. Then there are two test flows I started.
I have to maintain my own list remembering what deployment is for what. Specifying the flow name on creation would help me re-identifying it later.

User Acceptance Criteria
- [ ] I can set a custom flow name when deploying a flow with jcloud
- [ ] the flow name is shown when running jc list

**Comment by deepankarm** [comment]
@florian-hoenicke You can already pass `--name` field while deploying a Flow. The name passed for your Flows are `nowapi`, hence all Flows look the same :smile: 

![image](https://user-images.githubusercontent.com/9050737/192997020-4828d639-9fc8-41c7-9923-db987b51138e.png)

fyi, with new self-hosting deployments, we will be moving `name` field into the Flow YAML.

**Comment by florian-hoenicke** [comment]
Okay thanks - we will try this out
