### ISSUE TITLE
The error message is incorrect when running "jc list" with empty flow list

### ISSUE THREAD

**Issue by shazhou2015** [jina-ai/jcloud#9]
Reproduced steps:
1. install jcloud
2. login by github account
3. run `jc list`(make sure no flow is deployed on this time)

Result:
the output is:
`Listing all flows...Please login first.`

But if I deployed some flows firstly, everything worked well. So I guess the error message is incorrect.

**Comment by hanxiao** [comment]
yes, i also had this problem. But i guess is the server problem. because server returns 403 on an empty listing, which renders as "please login first"

https://github.com/jina-ai/jcloud/blob/main/jcloud/flow.py#L178-L179
