### ISSUE TITLE
JCloud should show local timestamp instead of UTC

### ISSUE THREAD

**Issue by zac-li** [jina-ai/jcloud#98]
![Image](https://user-images.githubusercontent.com/2687065/203681475-b685ee68-fc63-44eb-ab57-600caa72aeba.png)

Reported in Chinese community, that we should be consistent in Flow timestamps displaying; current our web UI display times in local timezone, we should do the same in `jc`

**Comment by npitsillos** [comment]
How should the heading `Created (UTC)` change here? Just write `Created (Local)` or show the timezone offset as in `GMT+8`
