### ISSUE TITLE
jc login doesn't show content.

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [jina-ai/jcloud#99]
as it showed below
![image](https://user-images.githubusercontent.com/84905965/203778176-1fd58fb2-43e4-44c3-bdab-2d16d009be6e.png)
it can be success loged in the website.
![image](https://user-images.githubusercontent.com/84905965/203778280-fd1f9798-c49a-441d-8115-176a015186bb.png)
however these isn't any info shown in terminal.
after about 5min it show this in terminal
```
Traceback (most recent call last):
  File "/home/kewei/miniconda3/bin/jc", line 8, in <module>
    sys.exit(main())
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/jcloud/__main__.py", line 21, in main
    getattr(api, args.jc_cli.replace('-', '_'))(args)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/jcloud/api.py", line 273, in login
    hubble.login()
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/hubble/__init__.py", line 68, in login
    Auth.login_sync(**kwargs)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/hubble/utils/auth.py", line 440, in login_sync
    response.raise_for_status()
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.hubble.jina.ai/v2/rpc/user.identity.grant.auto
Traceback (most recent call last):
  File "/home/kewei/miniconda3/bin/jc", line 8, in <module>
    sys.exit(main())
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/jcloud/__main__.py", line 21, in main
    getattr(api, args.jc_cli.replace('-', '_'))(args)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/jcloud/api.py", line 273, in login
    hubble.login()
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/hubble/__init__.py", line 68, in login
    Auth.login_sync(**kwargs)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/hubble/utils/auth.py", line 440, in login_sync
    response.raise_for_status()
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.hubble.jina.ai/v2/rpc/user.identity.grant.auto
```
how can I solve this?

**Comment by nomagick** [comment]
Hi.
What is your jcloud version?
Did you retry on this issue?
Are you using some kind of system-wide non-standard proxy software?
Could you try again without any proxy software or using another computer?

**Comment by Ethan-Chen-plus** [comment]
> Hi. What is your jcloud version? Did you retry on this issue? Are you using some kind of system-wide non-standard proxy software? Could you try again without any proxy software or using another computer?

I closed all my proxy and I have retried for several times, it doesn't works.
![image](https://user-images.githubusercontent.com/84905965/203788792-0c5a4d80-a1ea-4ffe-82d2-e168e52d12ab.png)

I searched from the docs:https://docs.jina.ai/jina-ai-cloud/login/
I see that the token would be saved locally.I wonder whether the reason is that I use WSL and the browser is my windows browser so the token saved in windows not WSL.
So I need some ways to manually save the token in my WSL.

**Comment by nomagick** [comment]
It should be able to work with WSL.

The command line uses a persistent HTTPS connection under the hood. 
When your browser shows the `Login Success` page, the command line should receive an event push from the server.
Somehow this didn't happen.

Could you try with another network environment without a proxy, like a 4G/5G hotspot?

If it's still not working, you can create a PAT [from the UI](https://cloud.jina.ai/settings/tokens) to walk around.
https://docs.jina.ai/jina-ai-cloud/login/#token-management

**Comment by Ethan-Chen-plus** [comment]
I tried with 5G hotspot from my mobile phone instead of WIFI I had used before.
However this doesn't change.
I used I 
```
export JINA_AUTH_TOKEN="d08ede1xxxxxxxxxxxx"
```
![image](https://user-images.githubusercontent.com/84905965/204072325-3e8bd78f-6acb-4940-b2be-8578d47b4275.png)

and then the login seems OK.
however there is another problem happened when I used `deploy`:
![image](https://user-images.githubusercontent.com/84905965/204072332-e3e88448-dcdf-4190-b140-10bd7a6fad1a.png)
```
Bad response: expecting 201, got 400 from server.
{
 "code": 400,
 "error": "cannot load Flow config failed to unmarshal flow config: error
unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go
struct field tmpType.executors of type string",
 "id": "",
 "status": {
  "phase": "",
  "conditions": null,
  "version": "",
  "protocol": "",
  "endpoints": null,
  "dashboards": null
 },
 "ctime": "0001-01-01T00:00:00Z",
 "utime": "0001-01-01T00:00:00Z"
}
```

I cloned it from this project:https://github.com/jina-ai/example-speech-to-image

**Comment by zac-li** [comment]
What's your Flow YAML in this case?

**Comment by zac-li** [comment]
can you try changing memory: 2 to memory: 2G (memory: 16 to memory: 16G) to see if that makes any difference?

**Comment by Ethan-Chen-plus** [comment]
I changed it, so this happened:
![image](https://user-images.githubusercontent.com/84905965/204460820-745fa86b-1b84-42f0-9f31-b02c5d9e0096.png)
so I used `vi flow.py`
![image](https://user-images.githubusercontent.com/84905965/204460968-bbca48b6-49d5-4a2d-9c66-eb3fe695d9ad.png)
and it seems that this project requires two GPUs.
how to solve it?

**Comment by deepankarm** [comment]
Hey @Ethan-Chen-plus, currently we have a few [restrictions](https://docs.jina.ai/fundamentals/jcloud/#restrictions) in JCloud, and we allow at max 1 GPU per Flow.

**Comment by zac-li** [comment]
Please reopen if needed.
